# Generated by Django 5.1.4 on 2025-02-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="views",
            new_name="total_views",
        ),
        migrations.AddField(
            model_name="post",
            name="unique_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
