# Generated by Django 5.1.4 on 2025-02-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_views_post_total_views_post_unique_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homepage_unique_views", models.PositiveIntegerField(default=0)),
                ("homepage_total_views", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
