# Generated by Django 5.1.4 on 2025-02-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_sitestats"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True, null=False),
        ),
    ]
