# Generated by Django 5.1.4 on 2025-02-13 19:28

from django.db import migrations
from django.utils.text import slugify

def update_slugs(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    for category in Category.objects.all():
        new_slug = slugify(category.name.replace("&", " and "))
        if category.slug != new_slug:
            category.slug = new_slug
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_category_slug"),
    ]

    operations = [
        migrations.RunPython(update_slugs),
    ]
